// Local UI harness: the real API on 127.0.0.1:8790, a throwaway database, one fixed test session.
import pg from 'pg';
const admin = new pg.Client({ connectionString: 'postgres://postgres:postgres@127.0.0.1:5434/postgres' });
await admin.connect(); await admin.query('DROP DATABASE IF EXISTS btc_harness WITH (FORCE)'); await admin.query('CREATE DATABASE btc_harness'); await admin.end();
process.env.DATABASE_URL = 'postgres://postgres:postgres@127.0.0.1:5434/btc_harness';
process.env.DELTA_LIVE_TRADING = '0';
const root = '/home/agent/test-delta/app/server/src';
const { initTradingService } = await import(`${root}/trading/service.ts`);
const { initStrategyStore } = await import(`${root}/http/routes/strategy.routes.ts`);
const { AuthStore } = await import(`${root}/auth/store.ts`);
const { AuthService } = await import(`${root}/auth/service.ts`);
const { Secrets } = await import(`${root}/auth/secrets.ts`);
const { hashPassword } = await import(`${root}/http/session.ts`);
const { buildApp } = await import(`${root}/http/app.ts`);
const { startTickerPoller, startTickerSocket, liveTickers } = await import(`${root}/market/delta.ts`);
const { flowSchema, startFlowSocket, flushTradeFlow, captureIvTerm, capturePerpSnapshot } = await import(`${root}/market/flow.ts`);
await initTradingService(); await initStrategyStore();
const store = await AuthStore.open();
await store.seedUser('harness', hashPassword('harness-only-not-a-real-password'), Date.now());
await store.createSession({ token: 'harness-session', stage: 'full', now: Date.now(), ttlMs: 8 * 3_600_000, ip: null, userAgent: null });
const app = await buildApp({ auth: new AuthService({ store, secrets: new Secrets('harness-secret'), now: Date.now }) });
startTickerPoller(8_000); startTickerSocket(); await flowSchema(); startFlowSocket((l) => console.log(l));
setInterval(() => { flushTradeFlow(Date.now()).catch(() => {}); }, 20_000);
setTimeout(() => { liveTickers().then((t) => captureIvTerm(t, Date.now())).catch(() => {}); capturePerpSnapshot(Date.now()).catch(() => {}); }, 10_000);
await app.listen({ port: 8790, host: '127.0.0.1' });
console.log('harness listening');
