/**
 * GENERATED by app/web/scripts/momentum-study.ts -- do not edit by hand.
 * The trend plan's record over the cached history, after taker fees
 * (0.05% a side): 2024-25 (in-sample) and 2026 (judged once). Shown beside the plan.
 */
export const TREND_MEASURED = {
  "from": "2024-01-10",
  "to": "2026-08-31",
  "feePerSide": 0.0005,
  "1H": {
    "ins": {
      "n": 558,
      "winRate": 0.3208,
      "netR": 0.1103,
      "t": 1.06,
      "worstRunR": -41.9
    },
    "oos": {
      "n": 184,
      "winRate": 0.3641,
      "netR": 0.0031,
      "t": 0.03,
      "worstRunR": -21.2
    },
    "bigMoveCapture": {
      "ins": 0.3795,
      "oos": 0.4457
    }
  },
  "4H": {
    "ins": {
      "n": 131,
      "winRate": 0.4046,
      "netR": 0.2888,
      "t": 1.85,
      "worstRunR": -8.3
    },
    "oos": {
      "n": 51,
      "winRate": 0.2745,
      "netR": 0.0277,
      "t": 0.11,
      "worstRunR": -13.8
    },
    "bigMoveCapture": {
      "ins": 0.4412,
      "oos": 0.4855
    }
  }
} as const;
