/**
 * The reference half of docs/, generated from the code.
 *
 * Hand-kept inventories drifted within days here -- FILE-INVENTORY.md missed
 * twenty files five days after it was written -- so the pages that say *what
 * exists* (files, HTTP routes, tables, environment) are rendered from the code,
 * and test/docs/docs.test.ts fails when a committed copy differs. The pages
 * that say *why* stay hand-written.
 *
 *   npm run docs      rewrite docs/reference/{files,api,schema,environment}.md
 *   npm test          fails on any drift, and on any link to a missing file
 *
 * Needs the test PostgreSQL (`deploy/test-db.sh up`): the schema page is read
 * back from a freshly migrated database, which is the only honest source for it.
 */
import { execFileSync } from 'node:child_process';
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, extname, join, posix, relative } from 'node:path';
import { fileURLToPath } from 'node:url';
import type { RouteOptions } from 'fastify';
import { ROOT } from '../paths.js';

const HEADER = '<!-- GENERATED by app/server/src/docs/gen-docs.ts -- do not edit; run `npm run docs` in app/server. -->';

export type Page = { path: string; body: string };

/** Repo-relative path of every generated page. */
export const GENERATED = [
  'docs/reference/files.md',
  'docs/reference/api.md',
  'docs/reference/schema.md',
  'docs/reference/environment.md',
] as const;

// ------------------------------------------------------------------ files

/**
 * Every file git knows about or would add, that is still on disk.
 *
 * Untracked-but-not-ignored files count, so a new module shows up before its
 * first commit and the test says so while the change is still in hand.
 */
export function repoFiles(): string[] {
  const out = execFileSync('git', ['ls-files', '--cached', '--others', '--exclude-standard', '-z'], {
    cwd: ROOT, encoding: 'utf8',
  });
  return [...new Set(out.split('\0').filter(Boolean))]
    .filter((f) => existsSync(join(ROOT, f)))
    .sort();
}

const isTest = (f: string) =>
  /\.test\.(ts|tsx|js|mjs)$/.test(f) || /(^|\/)tests?\//.test(f) || /(^|\/)test_[^/]+\.py$/.test(f);

const SKIPPED_EXT = new Set(['.png', '.jpg', '.jpeg', '.gif', '.ico', '.svg', '.webp', '.woff', '.woff2', '.ttf']);
const skipped = (f: string) =>
  SKIPPED_EXT.has(extname(f).toLowerCase())
  || /(^|\/)package-lock\.json$/.test(f)
  || (GENERATED as readonly string[]).includes(f);

/** The first sentence of a paragraph, capped for a table cell. */
export function firstSentence(paragraph: string): string {
  const text = paragraph.replace(/\s+/g, ' ').trim();
  if (!text) return '';
  const m = /^(.*?[.!?])(?=\s+[A-Z(`"*_\[]|\s*$)/.exec(text);
  const s = (m?.[1] ?? text).trim();
  return s.length > 200 ? `${s.slice(0, 197).trimEnd()}...` : s;
}

/** The first paragraph of a run of comment lines, markers stripped. */
function paragraphOf(lines: string[]): string {
  const out: string[] = [];
  for (const raw of lines) {
    const l = raw
      .replace(/^\s*(\/\*\*?|\*\/|\*|\/\/+|#+!?|""")\s?/, '')
      .replace(/\s*(\*\/|""")\s*$/, '');
    if (!l.trim()) {
      if (out.length) break;
      continue;
    }
    out.push(l.trim());
  }
  return out.join(' ');
}

/**
 * A code file's header comment, if it has one.
 *
 * This codebase puts a file's docblock after its imports, often directly above
 * the first declaration. So, before the first function or class: the first
 * comment that stands on its own (a blank line or another comment after it),
 * else the longest block of three lines or more (two for `//` lines). A comment
 * directly above a function or class documents that declaration, not the file
 * -- quoting it as the file's purpose would be a confident wrong answer --
 * unless it is the only one the file has, or the first it exports.
 */
function codeHeader(text: string): string {
  const lines = text.split('\n');
  const DECL = /^(export\s+)?(default\s+)?(async\s+)?(function|class)\b/;
  let i = 0;
  let inImport = false;
  let best: { size: number; p: string } | null = null;
  while (i < lines.length && i < 120) {
    const t = lines[i]!.trim();
    if (inImport) {
      if (/from\s+['"][^'"]+['"];?\s*$/.test(t) || /^\}\s*;?$/.test(t)) inImport = false;
      i++;
      continue;
    }
    if (DECL.test(t)) break;
    if (/^import\b/.test(t)) {
      if (!/;\s*$/.test(t) && !/from\s+['"]/.test(t) && !/^import\s+['"]/.test(t)) inImport = true;
      i++;
      continue;
    }
    const block = t.startsWith('/*');
    const line = t.startsWith('//');
    if (!block && !line) { i++; continue; }
    const start = i;
    if (block) {
      while (i < lines.length && !lines[i]!.includes('*/')) i++;
      i++;
    } else {
      while (i < lines.length && lines[i]!.trim().startsWith('//')) i++;
    }
    const next = lines[i]?.trim() ?? '';
    const standsAlone = next === '' || next.startsWith('/*') || next.startsWith('//');
    const size = i - start;
    const p = paragraphOf(lines.slice(start, i));
    if (!p || /^(eslint|@ts-|prettier)/i.test(p)) continue;
    if (standsAlone) return p;
    // Attached to a declaration: a candidate only if it is long, and not a
    // function's or a class's own doc. The longest wins -- a file's docblock is
    // nearly always bigger than the one-paragraph note on a constant beside it.
    const long = block ? size >= 3 : size >= 2;
    // The one function or class a module holds, or the first one it exports
    // (a component file's component): its doc, at length, is the module's.
    const onlyDecl = DECL.test(next)
      && (lines.filter((l) => DECL.test(l)).length === 1 || /^export\s/.test(next));
    if (long && (!DECL.test(next) || onlyDecl) && size > (best?.size ?? 0)) best = { size, p };
  }
  return best?.p ?? '';
}

/** Leading `#` comments, after a shebang. */
function hashHeader(text: string): string {
  const lines = text.split('\n');
  const out: string[] = [];
  for (const raw of lines) {
    const t = raw.trim();
    // A shebang, and parser directives (`# syntax=...`) are not prose.
    if (t.startsWith('#!') || /^#\s*(syntax|escape|check)=/.test(t)) continue;
    if (!t.startsWith('#')) {
      if (out.length || t !== '') break;
      continue;
    }
    out.push(t);
  }
  return paragraphOf(out);
}

/** A module docstring, or leading comments. */
function pyHeader(text: string): string {
  const m = /^\s*(?:#[^\n]*\n\s*)*(?:"""|''')([\s\S]*?)(?:"""|''')/.exec(text);
  if (m) return paragraphOf(m[1]!.split('\n'));
  return hashHeader(text);
}

/** What a file is for, in one sentence, from the file itself. Empty when it does not say. */
export function summaryOf(file: string, text: string): string {
  const ext = extname(file).toLowerCase();
  const name = posix.basename(file);
  let p = '';
  if (['.ts', '.tsx', '.js', '.mjs', '.cjs', '.css', '.php'].includes(ext)) p = codeHeader(text);
  else if (ext === '.py') p = pyHeader(text);
  else if (['.sh', '.yml', '.yaml', '.toml', '.conf', '.service'].includes(ext) || name.startsWith('Dockerfile')
    || name.endsWith('.example') || name.startsWith('.')) p = hashHeader(text);
  else if (ext === '.md') p = /^#\s+(.+)$/m.exec(text)?.[1] ?? '';
  else if (ext === '.txt') p = text.split('\n').find((l) => l.trim() !== '')?.trim() ?? '';
  // JSON takes no comments: say what kind of file it is, from its name.
  else if (ext === '.json') {
    p = name === 'package.json' ? `npm package: ${(JSON.parse(text) as { name?: string }).name ?? 'unnamed'}, its scripts and dependencies.`
      : /^tsconfig/.test(name) ? 'TypeScript compiler settings.'
        : name === 'knip.json' ? 'knip settings: the entry points it cannot find by itself.'
          : 'JSON settings.';
  } else if (ext === '.html') p = /<title>([^<]*)<\/title>/.exec(text)?.[1] ? `The page shell: "${/<title>([^<]*)<\/title>/.exec(text)![1]}".` : '';
  return firstSentence(p);
}

const cell = (s: string) => s.replace(/\|/g, '\\|');

/** A link from a page in docs/reference/ to a repo path. */
const fromReference = (repoPath: string) => posix.relative('docs/reference', repoPath).replace(/ /g, '%20');

export function renderFiles(files: readonly string[] = repoFiles()): string {
  const listed = files.filter((f) => !isTest(f) && !skipped(f));
  const tests = files.filter(isTest);

  const byDir = new Map<string, string[]>();
  for (const f of listed) {
    const d = posix.dirname(f);
    byDir.set(d, [...(byDir.get(d) ?? []), f]);
  }
  const testsByArea = new Map<string, number>();
  for (const f of tests) {
    const area = f.split('/').slice(0, 2).join('/');
    testsByArea.set(area, (testsByArea.get(area) ?? 0) + 1);
  }

  const out: string[] = [
    HEADER,
    '',
    '# Files',
    '',
    'Every source, config and script file in the repository, with the first sentence of its own header',
    'comment. A dash means the file has no header comment -- the fix is to write one, not to edit this page.',
    '',
    `${listed.length} files listed, ${tests.length} test files counted below, images and lockfiles left out.`,
    '',
    '## Test files',
    '',
    '| Area | Test files |',
    '|---|---:|',
    ...[...testsByArea].sort(([a], [b]) => a.localeCompare(b)).map(([a, n]) => `| \`${a}\` | ${n} |`),
    '',
  ];
  for (const [dir, fs] of [...byDir].sort(([a], [b]) => a.localeCompare(b))) {
    out.push(`## \`${dir === '.' ? '(root)' : `${dir}/`}\``, '', '| File | What it is |', '|---|---|');
    for (const f of fs) {
      const summary = summaryOf(f, readFileSync(join(ROOT, f), 'utf8'));
      out.push(`| [${cell(posix.basename(f))}](${fromReference(f)}) | ${summary ? cell(summary) : '--'} |`);
    }
    out.push('');
  }
  return out.join('\n');
}

// ------------------------------------------------------------------ API

export type RouteRow = { method: string; url: string; auth: string; file: string; what: string };

const ROUTE_FILE = /(app\/server\/src\/http\/routes\/[\w.-]+\.ts):(\d+)/;

/** The comment directly above a line, first sentence. */
function commentAbove(lines: readonly string[], lineNo: number): string {
  let i = lineNo - 2;
  if (i < 0) return '';
  const end = i;
  const t = lines[i]!.trim();
  if (t.startsWith('//')) {
    while (i >= 0 && lines[i]!.trim().startsWith('//')) i--;
    return firstSentence(paragraphOf(lines.slice(i + 1, end + 1)));
  }
  if (t.endsWith('*/')) {
    while (i >= 0 && !lines[i]!.includes('/*')) i--;
    return firstSentence(paragraphOf(lines.slice(i, end + 1)));
  }
  return '';
}

const SESSION: Record<string, string> = {
  public: 'none',
  totp: 'password step',
  setup: 'two-step setup',
  full: 'signed in',
};

/**
 * Every route, as Fastify registered it.
 *
 * Read from the app itself rather than parsed out of the source, so a route
 * added by any means is listed; the source line is taken from the stack at
 * registration only to find the comment that describes it.
 */
export async function collectRoutes(): Promise<RouteRow[]> {
  const { buildApp, routeAuthLevel } = await import('../http/app.js');
  const seen: RouteRow[] = [];
  const texts = new Map<string, string[]>();
  const app = await buildApp({
    onRoute: (r: RouteOptions) => {
      const methods = (Array.isArray(r.method) ? r.method : [r.method]).filter((m) => m !== 'HEAD');
      const at = ROUTE_FILE.exec(new Error().stack ?? '');
      const file = at?.[1] ?? '';
      let what = '';
      if (at) {
        if (!texts.has(file)) texts.set(file, readFileSync(join(ROOT, file), 'utf8').split('\n'));
        what = commentAbove(texts.get(file)!, Number(at[2]));
      }
      for (const method of methods) {
        seen.push({ method, url: r.url, auth: routeAuthLevel(r.url, r.config), file, what });
      }
    },
  });
  await app.ready();
  await app.close();
  return seen;
}

export function renderApi(routes: readonly RouteRow[]): string {
  const byFile = new Map<string, RouteRow[]>();
  for (const r of routes) byFile.set(r.file, [...(byFile.get(r.file) ?? []), r]);
  const out: string[] = [
    HEADER,
    '',
    '# HTTP API',
    '',
    'Every route the API registers, read from the Fastify app itself. All answer JSON under `/api`, behind',
    'one session cookie; the Session column is the sign-in stage a route needs (`routeAuthLevel` in',
    '`http/app.ts` -- a route is closed unless it says otherwise). Every POST, PUT, PATCH and DELETE must',
    'also carry an `Origin` or `Referer` naming the desk\'s own host.',
    '',
    'What: the first sentence of the comment directly above the route. A dash means there is none.',
    '',
    `${routes.length} routes.`,
    '',
  ];
  for (const [file, rs] of [...byFile].sort(([a], [b]) => a.localeCompare(b))) {
    out.push(`## [${posix.basename(file) || '(unknown file)'}](${fromReference(file)})`, '');
    out.push('| Method | Path | Session | What |', '|---|---|---|---|');
    for (const r of [...rs].sort((a, b) => a.url.localeCompare(b.url) || a.method.localeCompare(b.method))) {
      out.push(`| ${r.method} | \`${r.url}\` | ${SESSION[r.auth] ?? r.auth} | ${r.what ? cell(r.what) : '--'} |`);
    }
    out.push('');
  }
  return out.join('\n');
}

// ------------------------------------------------------------------ schema

/** Every schema the desk owns, migrated -- the same list `index.ts` runs, plus the ones migrated on first write. */
async function migrateEverything(): Promise<void> {
  const { initTradingService } = await import('../trading/service.js');
  const { marketSchema } = await import('../market/oi-history.js');
  const { errorLog } = await import('../observability/errors.js');
  const { optionSnapshotsSchema } = await import('../market/option-snapshots.js');
  const { flowSchema } = await import('../market/flow.js');
  const { initStrategyStore } = await import('../http/routes/strategy.routes.js');
  const { AuthStore } = await import('../auth/store.js');
  const { chainFeaturesSchema } = await import('../market/chain-features.js');
  const { bookHeatSchema } = await import('../market/book-heat.js');
  const { indexSchema } = await import('../market/index-1m.js');
  const { entrySchema } = await import('../entry/paper.js');
  const { gatesSchema } = await import('../entry/gates.js');
  const { alertsSchema } = await import('../entry/alerts.js');
  const { signalsSchema } = await import('../entry/signals.js');
  const { methodsSchema } = await import('../entry/catalogue.js');
  await initTradingService();
  await marketSchema();
  await errorLog().ready;
  await optionSnapshotsSchema();
  await flowSchema();
  await initStrategyStore();
  await AuthStore.open();
  await chainFeaturesSchema();
  await bookHeatSchema();
  await indexSchema();
  await entrySchema();
  await gatesSchema();
  await alertsSchema();
  await signalsSchema();
  await methodsSchema();
}

type Col = { table_name: string; column_name: string; data_type: string; udt_name: string; is_nullable: string; column_default: string | null; is_identity: string };

const UDT: Record<string, string> = {
  int2: 'smallint', int4: 'integer', int8: 'bigint', float4: 'real', float8: 'double precision',
  text: 'text', bool: 'boolean', jsonb: 'jsonb', numeric: 'numeric', varchar: 'varchar',
};

const typeOf = (c: Col) =>
  c.data_type === 'ARRAY' ? `${UDT[c.udt_name.slice(1)] ?? c.udt_name.slice(1)}[]`
    : c.data_type === 'character varying' ? 'varchar'
      : c.data_type;

/** `CREATE UNIQUE INDEX x ON public.t USING btree (a, b)` -> `x` unique (a, b). */
const indexOf = (name: string, def: string) => {
  const cols = /\((.*)\)(\s+WHERE\s+(.*))?$/.exec(def);
  const unique = /CREATE UNIQUE INDEX/.test(def) ? ' unique' : '';
  const where = cols?.[3] ? ` where ${cols[3]}` : '';
  return `\`${name}\`${unique} (${cols?.[1] ?? def})${where}`;
};

export async function renderSchema(): Promise<string> {
  await migrateEverything();
  const { rows } = await import('../db/pool.js');
  const cols = await rows<Col>(
    `SELECT c.table_name, c.column_name, c.data_type, c.udt_name, c.is_nullable, c.column_default, c.is_identity
       FROM information_schema.columns c
       JOIN information_schema.tables t ON t.table_schema = c.table_schema AND t.table_name = c.table_name
      WHERE c.table_schema = 'public' AND t.table_type = 'BASE TABLE'
      ORDER BY c.table_name, c.ordinal_position`,
  );
  const idx = await rows<{ tablename: string; indexname: string; indexdef: string }>(
    `SELECT tablename, indexname, indexdef FROM pg_indexes WHERE schemaname = 'public' ORDER BY tablename, indexname`,
  );
  const cons = await rows<{ table_name: string; name: string; def: string }>(
    `SELECT cl.relname AS table_name, co.conname AS name, pg_get_constraintdef(co.oid) AS def
       FROM pg_constraint co
       JOIN pg_class cl ON cl.oid = co.conrelid
       JOIN pg_namespace n ON n.oid = cl.relnamespace
      WHERE n.nspname = 'public' AND co.contype IN ('f', 'c')
      ORDER BY cl.relname, co.conname`,
  );
  const migrations = await rows<{ id: string }>('SELECT id FROM public.schema_migrations ORDER BY id');

  const tables = [...new Set(cols.map((c) => c.table_name))];
  const byArea = new Map<string, string[]>();
  for (const { id } of migrations) {
    const area = id.replace(/-\d{3}-.*$/, '');
    byArea.set(area, [...(byArea.get(area) ?? []), id]);
  }

  const out: string[] = [
    HEADER,
    '',
    '# Database schema',
    '',
    'The desk\'s PostgreSQL database as a fresh deploy creates it: every table in `public`, read back from',
    'the catalogue after every store\'s migrations have run. What each table is *for*, and why it is shaped',
    'the way it is, is in [database.md](database.md).',
    '',
    `${tables.length} tables, ${migrations.length} migrations.`,
    '',
    '## Migrations applied',
    '',
    '| Area | Migrations |',
    '|---|---|',
    ...[...byArea].map(([a, ids]) => `| ${a} | ${ids.map((i) => `\`${i}\``).join(', ')} |`),
    '',
    '## Tables',
    '',
    tables.map((t) => `[\`${t}\`](#${t})`).join(' · '),
    '',
  ];
  for (const t of tables) {
    out.push(`### ${t}`, '', '| Column | Type | Null | Default |', '|---|---|---|---|');
    for (const c of cols.filter((c) => c.table_name === t)) {
      const dflt = c.is_identity === 'YES' ? 'identity' : c.column_default ? `\`${cell(c.column_default)}\`` : '';
      out.push(`| \`${c.column_name}\` | ${typeOf(c)} | ${c.is_nullable === 'YES' ? 'yes' : ''} | ${dflt} |`);
    }
    const keys = [
      ...idx.filter((i) => i.tablename === t).map((i) => indexOf(i.indexname, i.indexdef)),
      ...cons.filter((c) => c.table_name === t).map((c) => `\`${c.name}\` ${c.def}`),
    ];
    if (keys.length) out.push('', ...keys.map((k) => `- ${cell(k)}`));
    out.push('');
  }
  return out.join('\n');
}

// ------------------------------------------------------------------ environment

/**
 * What each variable does. A variable read anywhere and missing here fails
 * the render, so a new one cannot ship without a line saying what it is.
 */
export const ENV_NOTES: Record<string, string> = {
  // the API process (app/server)
  PORT: 'HTTP port the API listens on. Default `8787`.',
  LOG_LEVEL: 'Fastify log level. Default `info`.',
  BUILD_TAG: 'The image tag this process was built as, shown on the screen as the running build. Compose sets it from `TAG`; unset when run by hand.',
  DATABASE_URL: 'PostgreSQL connection URL. **Required**: the desk will not start without somewhere to write its journal. Compose sets it from `POSTGRES_PASSWORD`.',
  CHAIN_DB: 'Path to `chain.db`, the harvester\'s read-only dataset. Default: `chain.db` at the repository root. Compose sets `/srv/data/chain.db`.',
  DELTA_API_KEY: 'Delta Exchange India API key for the account. Optional: without it market data still works and the desk stays on paper.',
  DELTA_API_SECRET: 'The secret for `DELTA_API_KEY`.',
  DELTA_LIVE_TRADING: '`0` or `false` forces paper and locks the mode switch. Anything else, or unset, allows live, and live is the starting mode once credentials exist (`config.ts`).',
  DESK_USER: 'Seeds the first sign-in user. Read once; afterwards the user lives in `auth_user`.',
  DESK_PASSWORD_HASH: 'Seeds the first user\'s password (scrypt hash from `npx tsx hash-password.mjs`). Never the password itself.',
  DESK_SESSION_SECRET: 'Seals the authenticator secret and recovery codes. Required for sign-in; rotating it means setting up two-step sign-in again (`npm run auth -- reset-2fa`).',
  DESK_ALLOWED_ORIGINS: 'Extra origins, comma-separated, allowed to send a change besides the desk\'s own host. Normally empty.',
  TG_TOKEN: 'Telegram bot token for fill and security alerts. Alerts are off unless both this and `TG_CHAT_ID` are set.',
  TG_CHAT_ID: 'The Telegram chat the alerts go to.',
  // docker compose and the deploy scripts (deploy/.env)
  POSTGRES_PASSWORD: 'Password of the `desk` database role. **Required** by compose.',
  TAG: 'Image tag compose runs. Set by `deploy.sh`; default `latest`.',
  WEB_BIND: 'Host address the web container is published on. Default `172.17.0.1` (the docker bridge), so only the edge proxy reaches it.',
  WEB_PORT: 'Host port for the web container. Default `8099`.',
  ADMINER_PORT: 'Host port for Adminer (profile `admin`). Default `8098`, bridge only.',
  DB_READONLY_PASSWORD: 'Password for `desk_ro`, the read-only role (`deploy/db-readonly-role.sh`).',
  DB_ADMIN_USER: 'A named admin login for a person (`deploy/db-admin-role.sh`).',
  DB_ADMIN_PASSWORD: 'Password for `DB_ADMIN_USER`.',
};

type EnvUse = { name: string; where: string[] };

/** `process.env.X` and `process.env['X']` across the server's source. */
export function serverEnv(files: readonly string[] = repoFiles()): EnvUse[] {
  const uses = new Map<string, Set<string>>();
  // Not this file: its own comments name the pattern it looks for.
  const src = files.filter((f) => f.startsWith('app/server/src/') && f.endsWith('.ts') && !f.startsWith('app/server/src/docs/'));
  for (const f of src) {
    const text = readFileSync(join(ROOT, f), 'utf8');
    for (const m of text.matchAll(/process\.env(?:\.([A-Z][A-Z0-9_]*)|\[['"]([A-Z][A-Z0-9_]*)['"]\])/g)) {
      const name = m[1] ?? m[2]!;
      uses.set(name, (uses.get(name) ?? new Set()).add(f));
    }
  }
  return [...uses].map(([name, where]) => ({ name, where: [...where].sort() })).sort((a, b) => a.name.localeCompare(b.name));
}

/** `${X}` / `${X:-...}` in the compose file, and every key in deploy/.env.example. */
export function deployEnv(): EnvUse[] {
  const uses = new Map<string, Set<string>>();
  const add = (name: string, where: string) => uses.set(name, (uses.get(name) ?? new Set()).add(where));
  const compose = 'deploy/docker-compose.yml';
  for (const m of readFileSync(join(ROOT, compose), 'utf8').matchAll(/\$\{([A-Z][A-Z0-9_]*)/g)) add(m[1]!, compose);
  const example = 'deploy/.env.example';
  for (const m of readFileSync(join(ROOT, example), 'utf8').matchAll(/^([A-Z][A-Z0-9_]*)=/gm)) add(m[1]!, example);
  return [...uses].map(([name, where]) => ({ name, where: [...where].sort() })).sort((a, b) => a.name.localeCompare(b.name));
}

export function renderEnvironment(server = serverEnv(), deploy = deployEnv()): string {
  const example = readFileSync(join(ROOT, 'app/server/.env.example'), 'utf8');
  const inExample = (n: string) => new RegExp(`^#?\\s*${n}=`, 'm').test(example);
  const note = (n: string) => {
    const s = ENV_NOTES[n];
    if (!s) throw new Error(`docs: no note for environment variable ${n} -- add one to ENV_NOTES in app/server/src/docs/gen-docs.ts`);
    return s;
  };
  const files = (ws: string[]) => ws.map((w) => `[${posix.basename(w)}](${fromReference(w)})`).join(', ');
  return [
    HEADER,
    '',
    '# Environment',
    '',
    'Every environment variable the code reads, found by scanning for it. The API reads its own once, at',
    'start (`app/server/src/config.ts` and the modules listed), from `app/server/.env` under compose; the',
    'deploy variables are read by docker compose and the scripts from `deploy/.env`.',
    '',
    '## The API process',
    '',
    '| Variable | Read in | In `app/server/.env.example` | What it does |',
    '|---|---|---|---|',
    ...server.map((e) => `| \`${e.name}\` | ${files(e.where)} | ${inExample(e.name) ? 'yes' : '**no**'} | ${cell(note(e.name))} |`),
    '',
    '## Compose and the deploy scripts',
    '',
    '| Variable | Read in | What it does |',
    '|---|---|---|',
    ...deploy.map((e) => `| \`${e.name}\` | ${files(e.where)} | ${cell(note(e.name))} |`),
    '',
  ].join('\n');
}

// ------------------------------------------------------------------ links

/**
 * Markdown files the link check covers: the front door and everything under
 * docs/ but the history, which records links as they were.
 */
export const linkedPages = (files: readonly string[] = repoFiles()) =>
  files.filter((f) => f === 'README.md'
    || (f.startsWith('docs/') && f.endsWith('.md') && !f.startsWith('docs/history/')));

/**
 * Relative links that point at nothing. External links, anchors within the
 * page and links inside code spans or fences are not checked.
 */
export function brokenLinks(files: readonly string[] = repoFiles()): string[] {
  const broken: string[] = [];
  for (const page of linkedPages(files)) {
    const text = readFileSync(join(ROOT, page), 'utf8')
      .replace(/```[\s\S]*?```/g, '')
      .replace(/`[^`\n]*`/g, '');
    for (const m of text.matchAll(/\]\(([^)\s]+)(?:\s+"[^"]*")?\)/g)) {
      const target = m[1]!;
      if (/^[a-z]+:/i.test(target) || target.startsWith('#')) continue;
      const path = decodeURIComponent(target.split('#')[0]!);
      if (!existsSync(join(ROOT, posix.dirname(page), path))) broken.push(`${page} -> ${target}`);
    }
  }
  return broken;
}

/**
 * `docs/<name>.md` named in code or config, where no such page exists.
 * `<rev>:docs/<name>.md` -- a page in git history -- is allowed.
 *
 * The dated history and the research reports are left out: they record what
 * was true when they were written, including pages that have since moved.
 */
export function brokenDocMentions(files: readonly string[] = repoFiles()): string[] {
  const out: string[] = [];
  const TEXT = /\.(ts|tsx|js|mjs|py|sh|yml|yaml|conf|md|css|php|service)$|(^|\/)Dockerfile[^/]*$/;
  for (const f of files) {
    if (!TEXT.test(f) || f.startsWith('docs/history/') || f.startsWith('research/')) continue;
    const text = readFileSync(join(ROOT, f), 'utf8');
    for (const m of text.matchAll(/\bdocs\/[A-Za-z0-9_./-]+\.md\b/g)) {
      // `git show <rev>:docs/x.md` names a page in history, on purpose.
      if (text[m.index! - 1] === ':') continue;
      if (!existsSync(join(ROOT, m[0]))) out.push(`${f} -> ${m[0]}`);
    }
  }
  return [...new Set(out)];
}

// ------------------------------------------------------------------ all

export async function renderReference(): Promise<Page[]> {
  const files = repoFiles();
  // The schema first: migrating everything is what the route build needs too.
  const schema = await renderSchema();
  return [
    { path: 'docs/reference/files.md', body: renderFiles(files) },
    { path: 'docs/reference/api.md', body: renderApi(await collectRoutes()) },
    { path: 'docs/reference/schema.md', body: schema },
    { path: 'docs/reference/environment.md', body: renderEnvironment(serverEnv(files)) },
  ];
}

const isMain = process.argv[1] !== undefined && fileURLToPath(import.meta.url) === process.argv[1];
if (isMain) {
  const pages = await renderReference();
  for (const p of pages) {
    const at = join(ROOT, p.path);
    mkdirSync(dirname(at), { recursive: true });
    writeFileSync(at, p.body);
    console.log(`wrote ${relative(process.cwd(), at)}`);
  }
  const { closePool } = await import('../db/pool.js');
  await closePool();
}
