// GENERATED by app/web/scripts/smc-study.ts -- do not edit; rerun the study instead.
// What the desk's SMC rules (DESK_SMC_OPTIONS) did over the cached 5m history, after fees.
// See research/SMC-STUDY.txt for the method, the funnel and the variants.

export const SMC_MEASURED = {
  "from": "2024-01-10",
  "to": "2026-08-31",
  "feePerSide": 0.0005,
  "all": {
    "n": 2425,
    "winRate": 0.3694845360824742,
    "grossR": -0.05971881715911446,
    "netR": -0.4528820109471351
  },
  "heldOut2026": {
    "n": 619,
    "winRate": 0.35218093699515346,
    "grossR": -0.14730233880681765,
    "netR": -0.5754039062645971
  },
  "bigMoveCapture": 0.08181413961760782
} as const;
