// GENERATED by app/web/scripts/smc-study.ts -- do not edit; rerun the study instead.
// What the desk's SMC rules (DESK_SMC_OPTIONS) did over the cached 5m history, after fees.
// See research/SMC-STUDY.txt for the method, the funnel and the variants.

export const SMC_MEASURED = {
  "from": "2024-01-10",
  "to": "2026-08-31",
  "feePerSide": 0.0005,
  "all": {
    "n": 5245,
    "winRate": 0.45681601525262155,
    "grossR": -0.03950191263367906,
    "netR": -0.3454989665891724
  },
  "heldOut2026": {
    "n": 1336,
    "winRate": 0.4416167664670659,
    "grossR": -0.11470225887206355,
    "netR": -0.4556172095368687
  },
  "bigMoveCapture": 0.3619386393952868
} as const;
