// GENERATED by app/web/scripts/smc-study.ts -- do not edit; rerun the study instead.
// What the desk's SMC rules (DESK_SMC_OPTIONS) did over the cached 5m history, after fees.
// See research/SMC-STUDY.txt for the method, the funnel and the variants.

export const SMC_MEASURED = {
  "from": "2024-01-10",
  "to": "2026-08-31",
  "feePerSide": 0.0005,
  "all": {
    "n": 4876,
    "winRate": 0.31009023789991796,
    "grossR": -0.0771330429222344,
    "netR": -0.4008740635516654
  },
  "heldOut2026": {
    "n": 1205,
    "winRate": 0.3053941908713693,
    "grossR": -0.12181328721527254,
    "netR": -0.47129612057446096
  },
  "bigMoveCapture": 0.30057803468208094
} as const;
