import { forwardRef, useState } from 'react';
import { ChevronDown, ChevronRight } from 'lucide-react';
import type { TfRead } from '@/lib/smc/context';
import type { Readout } from '@/lib/smc/readout';
import { SMC_MEASURED } from '@/lib/smc/measured.data';

const fmt = (p: number) => Math.round(p).toLocaleString('en-US');
const pct = (v: number) => `${Math.round(v * 100)}%`;
const IST_HM = new Intl.DateTimeFormat('en-IN', { timeZone: 'Asia/Kolkata', day: 'numeric', month: 'short', hour: '2-digit', minute: '2-digit', hour12: false });
const r1 = (v: number) => `${v >= 0 ? '+' : '−'}${Math.abs(v).toFixed(1)}R`;

type Shown = { open: number; high: number; low: number; close: number; when: string; hovering: boolean };

/**
 * The chart's corner readout: the live setup and what it is waiting for, the
 * plan when there is one, the timeframe context, and this chart's own record.
 * Inside the chart, over the candles' quietest corner, and folds to one line.
 */
export const ChartHud = forwardRef<HTMLDivElement, {
  open: boolean;
  onToggle: () => void;
  tf: string;
  read: Readout;
  context: readonly TfRead[];
  candle: Shown | null;
}>(function ChartHud({ open, onToggle, tf, read, context, candle }, ref) {
  const up = candle ? candle.close >= candle.open : true;
  return (
    <div ref={ref} className={`pc-hud pc-hud-${read.tone}`} aria-label="Setup readout">
      <button type="button" className="pc-hud-head" onClick={onToggle} aria-expanded={open}>
        {open ? <ChevronDown size={13} aria-hidden /> : <ChevronRight size={13} aria-hidden />}
        <b>{read.headline}</b>
        <span className="pc-hud-tf">{tf}</span>
      </button>
      {open && (
        <div className="pc-hud-body">
          <p className="pc-hud-detail">{read.detail}</p>

          {read.confirmations.length > 0 && (
            <ul className="pc-hud-checks" aria-label="Confirmations">
              {read.confirmations.map((c) => (
                <li key={c.name} className={c.ok ? 'ok' : 'wait'}>{c.ok ? '✓' : '○'} {c.name}</li>
              ))}
            </ul>
          )}

          {read.plan && (
            <div className="pc-hud-plan" aria-label="Trade plan">
              <span><i>{read.plan.filled ? 'Entry' : 'Plan'}</i> {fmt(read.plan.entry)}{read.plan.filled ? ' ✓' : ''}</span>
              <span className="sl">
                <i>SL</i> {fmt(read.plan.stop)} <small>{read.plan.stopMoved ? `moved · ${read.plan.stopNote}` : `−${fmt(read.plan.risk)} pts · −1R · ${read.plan.stopNote ?? ''}`}</small>
              </span>
              {read.plan.targets.map((t, k) => (
                <span key={k} className="tp" title={t.reason}>
                  <i>TP{k + 1}</i> {fmt(t.price)}{t.hit ? ' ✓' : ''} <small>+{fmt(Math.abs(t.price - read.plan!.entry))} pts · {r1(t.rNow)} · {t.reason}</small>
                </span>
              ))}
              {read.plan.filled && (
                <span className="pnl">
                  <i>Realised</i> {r1(read.plan.realisedR)} <small>({Math.round((1 - read.plan.openShare) * 100)}% closed)</small>
                  {' · '}<i>Open</i> {r1(read.plan.openR)} <small>on {Math.round(read.plan.openShare * 100)}%</small>
                </span>
              )}
            </div>
          )}

          {context.length > 0 && (
            <div className="pc-hud-ctx" aria-label="Timeframe context">
              {context.map((c) => (
                <span key={c.tf} className={c.trend === 'bull' ? 'up' : c.trend === 'bear' ? 'down' : ''}
                  title={c.last ? `${c.last.kind} ${c.last.dir === 'bull' ? 'up' : 'down'}, ${c.last.barsAgo} candles ago` : 'No break yet'}>
                  <b>{c.tf}</b> {c.trend === 'bull' ? '▲' : c.trend === 'bear' ? '▼' : '–'} {c.role}
                </span>
              ))}
            </div>
          )}

          {/*
            What these exact rules did over the cached history, after fees -- beside every setup,
            so a plan on the chart is never read as a promise. Regenerated by scripts/smc-study.ts.
          */}
          {(read.plan || read.confirmations.length > 0) && (
            <p className="pc-hud-measured" title={`${SMC_MEASURED.from} → ${SMC_MEASURED.to}, fees ${SMC_MEASURED.feePerSide * 100}% a side. research/SMC-STUDY.txt`}>
              Measured {SMC_MEASURED.from.slice(0, 4)}–{SMC_MEASURED.to.slice(2, 4)}: {SMC_MEASURED.all.n} trades · win {pct(SMC_MEASURED.all.winRate)} · {r1(SMC_MEASURED.all.netR)}/trade after fees
              (2026 {r1(SMC_MEASURED.heldOut2026.netR)}). Information, not a signal.
            </p>
          )}

          {!read.plan && read.refused && (
            <div className="pc-hud-refused" aria-label="Last plan refused">
              <p><b>Last {read.refused.dir === 'bull' ? 'long' : 'short'} refused</b> · {IST_HM.format(read.refused.time * 1000)}</p>
              <ul className="pc-hud-checks">
                {read.refused.checks.map((c) => <li key={c.name} className={c.ok ? 'ok' : 'no'}>{c.ok ? '✓' : '✗'} {c.name}</li>)}
              </ul>
              <p className="pc-hud-why">{read.refused.reason}</p>
            </div>
          )}

          {read.history.length > 0 && <TradeHistory rows={read.history} />}

          {read.record && (
            <p className="pc-hud-record" title="Setups this chart's candles produced and completed, each decided without seeing what came after it">
              This chart: {read.record.n} trade{read.record.n === 1 ? '' : 's'} · TP1 {pct(read.record.tp1Rate)} · SL {pct(read.record.stopRate)} · avg {r1(read.record.avgR)} · MFE {read.record.avgMfeR.toFixed(1)}R · MAE {read.record.avgMaeR.toFixed(1)}R
            </p>
          )}

          {candle && (
            <p className="pc-hud-ohlc">
              <span>{candle.hovering ? candle.when : 'Last'}</span>
              <span>O {fmt(candle.open)}</span><span>H {fmt(candle.high)}</span><span>L {fmt(candle.low)}</span>
              <span className={up ? 'up' : 'down'}>C {fmt(candle.close)}</span>
            </p>
          )}
        </div>
      )}
    </div>
  );
});

/** This chart's completed trades, newest first -- folded until asked for. */
function TradeHistory({ rows }: { rows: Readout['history'] }) {
  const [open, setOpen] = useState(false);
  return (
    <div className="pc-hud-history">
      <button type="button" className="pc-hud-sub" aria-expanded={open} onClick={() => setOpen(!open)}>
        {open ? <ChevronDown size={12} aria-hidden /> : <ChevronRight size={12} aria-hidden />} Trades ({rows.length})
      </button>
      {open && (
        <div className="pc-hud-table-wrap">
          <table className="pc-hud-table">
            <thead>
              <tr><th>Time (IST)</th><th>Side</th><th>Entry</th><th>SL</th><th>TP1</th><th>Exit</th><th>Result</th><th>MFE</th><th>MAE</th><th>Min</th><th>Path</th></tr>
            </thead>
            <tbody>
              {rows.slice(0, 8).map((r) => (
                <tr key={r.id}>
                  <td>{IST_HM.format(r.time * 1000)}</td>
                  <td className={r.dir === 'bull' ? 'up' : 'down'}>{r.dir === 'bull' ? 'Long' : 'Short'}</td>
                  <td>{fmt(r.entry)}</td><td>{fmt(r.stop)}</td><td>{fmt(r.tp1)}</td><td>{fmt(r.exit)}</td>
                  <td className={r.resultR > 0.05 ? 'up' : r.resultR < -0.05 ? 'down' : ''}>{r1(r.resultR)}</td>
                  <td>{r.mfeR.toFixed(1)}R</td><td>{r.maeR.toFixed(1)}R</td><td>{r.minutes}</td>
                  <td className="path">{r.path}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}
    </div>
  );
}
